#!/bin/sh

#--------------------------------------------------------------
# Docker CMD
#--------------------------------------------------------------
envsubst '$$PROXY_PROTOCOL$$PROXY_DOMAIN$$PROXY_PORT$$PROXY_NAMESERVER$$PROXY_ROBOTS_TXT' < /etc/nginx/conf.d/proxy.template.conf > /etc/nginx/conf.d/proxy.conf
rm -f /etc/nginx/conf.d/proxy.template.conf
rm -f /etc/nginx/nginx.template.conf
nginx -g 'daemon off;'
