#!/bin/sh

#--------------------------------------------------------------
# Docker CMD
#--------------------------------------------------------------
envsubst '$$PROXY_DOMAIN$$PROXY_NAMESERVER' < /etc/nginx/conf.d/proxy.template.conf > /etc/nginx/conf.d/proxy.conf
envsubst '$$PROXY_ROLE' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf
rm -f /etc/nginx/conf.d/proxy.template.conf
rm -f /etc/nginx/nginx.template.conf
nginx -g 'daemon off;'
